### ISSUE TITLE
Speed Up AGC

### ISSUE THREAD

**Issue by N5QM** [BrandMeister/hoseline#11] opened 2016-04-01 03:50 UTC
Hello!

Is there a way to speed up the AGC action?  It seems to lag a little bit and tends to peak far into the red area and makes an "interesting" noise when that happens..  :-)

**Comment by tehmaze** [comment] 2016-04-03 18:03
Noise does not come from the AGC but from the decoder. Needs more investigation.

**Comment by tehmaze** [comment] 2016-04-03 18:06
To answer your question, sample rate is 8kHz with PCM16 samples.

**Comment by N5QM** [comment] 2016-04-03 23:49
Ok..  In the display when the noise comes, the dots reach up into the red and by disabling the AGC and moving the gain number down it seems to resolve the issue.

This is why I assumed it was an AGC issue.

**Comment by tehmaze** [comment] 2016-04-05 22:20
Looks like this may be a duplicate of #6

**Comment by tehmaze** [comment] 2016-04-12 23:06
Audio compressor added in 2.x that should take care of most of the peak noise.

**Closed by tehmaze** 2016-04-12 23:06 UTC
