### ISSUE TITLE
firefox problem

### ISSUE THREAD

**Issue by F20783** [BrandMeister/hoseline#8] opened 2016-03-28 16:37 UTC
I have a problem with firefox.
the first time i's ok it's possible to listen, but now it's not possible, I test with google chrome, and it's ok, I retest with firefox, but it's not possible I don't see list of connected, I see just welcome message and if I click on talk group I have waiting server..... 10minutes and same message

**Comment by PD1WP** [comment] 2016-03-29 08:34
The same here

**Comment by zarya** [comment] 2016-03-29 10:53
Could you guys give some more information on platforms and installed plugins versions stuff like that.

All that we could test on it works we cant reproduce the problem with the hardware we have.

**Comment by tehmaze** [comment] 2016-03-29 14:36
We are having troubles reproducing locally on recent versions of Firefox. Can you please tell me exactly:

 * What platform
 * What browser version (available from `Firefox` menu, `About Firefox`)

**Comment by PD1WP** [comment] 2016-03-29 14:53
I'm using a Samsung Galaxy S5 SM-G900F with Android 5.0, Samsung Galaxy Tab S 10.5 SM-T800 Android 5.02 and a i7-4790 with Windows 10. My S5 used a Firefox browser version 45.0.1, Flashfox Pro (same developer) version 44.0, Samsung stock browser version 4.0.10-51 and Dolphin Browser version 11.5.5.My i7 works great.  Is this enough information?  Thank you for your time and support. Wilfred Pontfoort, Apeldoorn  the Netherlands.


Verzonden vanaf mijn Samsung-apparaat

-------- Oorspronkelijk bericht --------
Van: tehmaze <notifications@github.com>
Datum: 29-03-2016  16:36  (GMT+01:00)
Aan: BrandMeister/hoseline <hoseline@noreply.github.com>
Cc: PD1WP <w_pontfoort@hotmail.com>
Onderwerp: Re: [BrandMeister/hoseline] firefox problem (#8)

We are having troubles reproducing locally on recent versions of Firefox. Can you please tell me exactly:

 * What platform
 * What browser version (available from `Firefox` menu, `About Firefox`)

---

**Comment by tehmaze** [comment] 2016-03-29 15:31
Thanks for the report @PD1WP. We've added error tracking to the pages just now, which should give us more insight into what's happening in browsers that are not (yet?) fully supported.

**Comment by tehmaze** [comment] 2016-03-29 15:49
@PD1WP think I found one of the issues you are seeing, from User-Agent `Mozilla/5.0 (Android 5.0.1; Mobile; rv:45.0) Gecko/45.0 Firefox/45.0`:

```javascript
{"stack":[{"functionName":"jvm.SVGElement.prototype.getBBox","fileName":"http://hose.brandmeister.network/static/js/jquery-jvectormap-2.0.3.min.js","lineNumber":1,"columnNumber":8996,"so
urce":"jvm.SVGElement.prototype.getBBox@http://hose.brandmeister.network/static/js/jquery-jvectormap-2.0.3.min.js:1:8996"}...
```

The world map is throwing errors. I wrapped it in try/catch so the page will continue to load if the map setup failed.

**Comment by F20783** [comment] 2016-03-29 16:02
my platform is firefox 45.0 ubuntu canonical 1.0 but today is ok it's working !!!

**Comment by PD1WP** [comment] 2016-03-29 16:54
Verzonden vanaf mijn Samsung-apparaat

-------- Oorspronkelijk bericht --------
Van: tehmaze <notifications@github.com>
Datum: 29-03-2016  17:31  (GMT+01:00)
Aan: BrandMeister/hoseline <hoseline@noreply.github.com>
Cc: PD1WP <w_pontfoort@hotmail.com>
Onderwerp: Re: [BrandMeister/hoseline] firefox problem (#8)

Thanks for the report @PD1WP. We've added error tracking to the pages just now, which should give us more insight into what's happening in browsers that are not (yet?) fully supported.

---

**Comment by tehmaze** [comment] 2016-03-29 20:26
Closing this issue since recent Firefox (on PC at least) is confirmed working. Please open a different issues for other devices that are not working like they should.

**Closed by tehmaze** 2016-03-29 20:26 UTC
Labels: bug, help wanted
